const products = [
  {
    id: 1,
    name: 'Маска сварочная',
    internalName: 'Маска сварочная чёрная',
    kaspiName: 'Маска сварочная защитная ESAB',
    kaspiArticle: 'ESAB-MASK-001',
    article: 'MSV-001',
    costPrice: '2500.00',
    sellingPrice: '4500.00',
    currentStock: 15,
    minStock: 5,
    categoryId: 1,
    image: null,
    category: { id: 1, name: 'Сварочное оборудование' },
    suppliers: [{ id: 1, name: 'ТОО Металл Торг', ProductSupplier: { supplierPrice: '2500.00' } }],
    variations: [],
  },
  {
    id: 2,
    name: 'Электроды 3мм',
    internalName: 'Электроды сварочные 3мм пачка',
    kaspiName: 'Электроды сварочные МР-3 d3мм 5кг',
    kaspiArticle: 'ELEKTROD-MR3-3MM',
    article: 'EL-003',
    costPrice: '1800.00',
    sellingPrice: '2800.00',
    currentStock: 2,
    minStock: 10,
    categoryId: 1,
    image: null,
    category: { id: 1, name: 'Сварочное оборудование' },
    suppliers: [{ id: 1, name: 'ТОО Металл Торг', ProductSupplier: { supplierPrice: '1800.00' } }],
    variations: [],
  },
  {
    id: 3,
    name: 'Болгарка 125мм',
    internalName: 'Болгарка угловая 125мм',
    kaspiName: 'Угловая шлифмашина Makita GA5030',
    kaspiArticle: 'MAKITA-GA5030',
    article: 'BLG-125',
    costPrice: '15000.00',
    sellingPrice: '22000.00',
    currentStock: 7,
    minStock: 3,
    categoryId: 2,
    image: null,
    category: { id: 2, name: 'Инструмент' },
    suppliers: [
      { id: 2, name: 'ИП Строй Комплект', ProductSupplier: { supplierPrice: '15000.00' } },
    ],
    variations: [],
  },
  {
    id: 4,
    name: 'Перчатки рабочие',
    internalName: 'Перчатки хб с ПВХ точками',
    kaspiName: 'Перчатки рабочие ХБ с ПВХ покрытием, 10 класс',
    kaspiArticle: 'GLOVE-HB-PVX-10',
    article: 'PRG-001',
    costPrice: '120.00',
    sellingPrice: '250.00',
    currentStock: 0,
    minStock: 20,
    categoryId: 3,
    image: null,
    category: { id: 3, name: 'СИЗ' },
    suppliers: [{ id: 1, name: 'ТОО Металл Торг', ProductSupplier: { supplierPrice: '120.00' } }],
    variations: [],
  },
  {
    id: 5,
    name: 'Каска строительная',
    internalName: 'Каска ABS жёлтая',
    kaspiName: 'Каска защитная строительная ABS пластик',
    kaspiArticle: 'KASKA-ABS-YEL',
    article: 'KSK-001',
    costPrice: '900.00',
    sellingPrice: '1500.00',
    currentStock: 30,
    minStock: 10,
    categoryId: 3,
    image: null,
    category: { id: 3, name: 'СИЗ' },
    suppliers: [{ id: 2, name: 'ИП Строй Комплект', ProductSupplier: { supplierPrice: '900.00' } }],
    variations: [],
  },
];

const suppliers = [
  {
    id: 1,
    name: 'ТОО Металл Торг',
    phone: '+77001234567',
    whatsapp: '+77001234567',
    address: 'Алматы, Байсад, Сектор A, Ряд 3, Контейнер 15',
    debt: '0.00',
    isActive: true,
    email: 'metaltorg@example.com',
    products: [
      { id: 1, name: 'Маска сварочная', ProductSupplier: { supplierPrice: '2500.00' } },
      { id: 2, name: 'Электроды 3мм', ProductSupplier: { supplierPrice: '1800.00' } },
      { id: 4, name: 'Перчатки рабочие', ProductSupplier: { supplierPrice: '120.00' } },
    ],
  },
  {
    id: 2,
    name: 'ИП Строй Комплект',
    phone: '+77009876543',
    whatsapp: '+77009876543',
    address: 'Алматы, Байсад, Сектор B, Ряд 1, Контейнер 7',
    debt: '45000.00',
    isActive: true,
    email: null,
    products: [
      { id: 3, name: 'Болгарка 125мм', ProductSupplier: { supplierPrice: '15000.00' } },
      { id: 5, name: 'Каска строительная', ProductSupplier: { supplierPrice: '900.00' } },
    ],
  },
  {
    id: 3,
    name: 'ТОО Техснаб',
    phone: '+77771112233',
    whatsapp: null,
    address: 'Алматы, Байсад, Сектор C, Ряд 2, Контейнер 3',
    debt: '120000.00',
    isActive: true,
    email: null,
    products: [],
  },
];

const categories = [
  { id: 1, name: 'Сварочное оборудование', description: null, parentId: null, isActive: true },
  { id: 2, name: 'Инструмент', description: null, parentId: null, isActive: true },
  { id: 3, name: 'СИЗ', description: 'Средства индивидуальной защиты', parentId: null, isActive: true },
];

const orders = [
  {
    id: 1,
    orderNumber: 'ORD-2026-001',
    status: 'Подтверждена',
    totalAmount: '28000.00',
    paidAmount: '28000.00',
    paymentStatus: 'Оплачено',
    notes: 'Срочная заявка',
    createdAt: '2026-04-10T08:00:00.000Z',
    updatedAt: '2026-04-10T12:00:00.000Z',
    supplierId: 1,
    supplier: { id: 1, name: 'ТОО Металл Торг', phone: '+77001234567', whatsapp: '+77001234567' },
    items: [
      { id: 1, productId: 1, quantity: 5, priceAtPurchase: '2500.00', product: { id: 1, name: 'Маска сварочная', article: 'MSV-001' } },
      { id: 2, productId: 2, quantity: 3, priceAtPurchase: '1800.00', product: { id: 2, name: 'Электроды 3мм', article: 'EL-003' } },
    ],
    payments: [{ id: 1, amount: '28000.00', paymentMethod: 'bank_transfer', createdAt: '2026-04-10T12:00:00.000Z' }],
  },
  {
    id: 2,
    orderNumber: 'ORD-2026-002',
    status: 'Создана',
    totalAmount: '112000.00',
    paidAmount: '0.00',
    paymentStatus: 'Не оплачено',
    notes: null,
    createdAt: '2026-04-13T09:30:00.000Z',
    updatedAt: '2026-04-13T09:30:00.000Z',
    supplierId: 2,
    supplier: { id: 2, name: 'ИП Строй Комплект', phone: '+77009876543', whatsapp: '+77009876543' },
    items: [
      { id: 3, productId: 3, quantity: 5, priceAtPurchase: '15000.00', product: { id: 3, name: 'Болгарка 125мм', article: 'BLG-125' } },
      { id: 4, productId: 5, quantity: 10, priceAtPurchase: '900.00', product: { id: 5, name: 'Каска строительная', article: 'KSK-001' } },
    ],
    payments: [],
  },
];

const users = [
  { id: 1, name: 'Администратор', email: 'admin@example.com', role: 'admin', isActive: true, createdAt: '2026-01-01T00:00:00.000Z' },
  { id: 2, name: 'Иван Оператор', email: 'operator@example.com', role: 'operator', isActive: true, createdAt: '2026-02-01T00:00:00.000Z' },
  { id: 3, name: 'Баха Сборщик', email: 'collector@example.com', role: 'collector', isActive: true, createdAt: '2026-03-01T00:00:00.000Z' },
];

const stockAnalytics = {
  summary: {
    total: 5,
    critical: 1,
    low: 1,
    medium: 0,
    good: 3,
  },
  products: products.map(p => ({
    ...p,
    stockStatus: p.currentStock === 0 ? 'critical' : p.currentStock <= p.minStock ? 'low' : p.currentStock <= p.minStock * 2 ? 'medium' : 'good',
  })),
};

module.exports = { products, suppliers, categories, orders, users, stockAnalytics };
